version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: axity
      RABBITMQ_DEFAULT_PASS: axity
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - '15672:15672'
      - '5672:5672'
